name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  animated_splash_screen: ^1.3.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/cat1.jpg
    - assets/about1.jpg
    - assets/photo.jpg
    - assets/photo2.jpg
    - assets/quote2.jpg